### ISSUE TITLE
feat: Sampling Service

### ISSUE THREAD

**Issue by anoushk1234** [tinydancer-io/tinydancer#2]
**Tasks**
- [x] Add Rocks db to store shreds with purge config

**Tests**
- [ ] Simulate fake shreds
- [ ] Simulate real shreds
- [ ] Simulate invalid signature
- [ ] Simulate bad quantity of shreds

**Docs**
- [x] Write core docs for this
